# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI application to interface with State Space"
  homepage "https://state.space"
  version "0.0.17"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/state-space/cli/releases/download/v0.0.17/state-space_darwin_x86_64"
      sha256 "dc7516d0dcc4f30545d5362e9cbc7169afe25b7b57a3441f44b919dc0c3b29b8"

      def install
        bin.install "state-space_darwin_x86_64" => "state-space"
      end
    end
    on_arm do
      url "https://github.com/state-space/cli/releases/download/v0.0.17/state-space_darwin_arm64"
      sha256 "c4cc9b189d77b9c7659dd97af68999a8c2fe736f8f341577aa0ca421d6133d5e"

      def install
        bin.install "state-space_darwin_arm64" => "state-space"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/state-space/cli/releases/download/v0.0.17/state-space_linux_x86_64"
        sha256 "81b478f7f4e6df795a38b7a6a09e9a2bc67dd2f0a5d63b4640d5b0db9aeffdbf"

        def install
          bin.install "state-space_linux_x86_64" => "state-space"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/state-space/cli/releases/download/v0.0.17/state-space_linux_arm64"
        sha256 "dce37c59ae65070193ae157a935cb5e82fbf3415d848ac88c404c5e6c449d421"

        def install
          bin.install "state-space_linux_arm64" => "state-space"
        end
      end
    end
  end

  test do
    system "#{bin}/state-space --version"
  end
end
