# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI application to interface with State Space"
  homepage "https://state.space"
  version "0.0.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/state-space/cli/releases/download/v0.0.11/state-space_darwin_x86_64"
      sha256 "3469ba91025779a45cec6af0b919732065849fa3a99304bfad403476b34ec6cc"

      def install
        bin.install "state-space_darwin_x86_64" => "state-space"
      end
    end
    on_arm do
      url "https://github.com/state-space/cli/releases/download/v0.0.11/state-space_darwin_arm64"
      sha256 "6899a8cdb1e98b025e48c74953a6c3511c14a351684a6f0fd2a16b9f9f713914"

      def install
        bin.install "state-space_darwin_arm64" => "state-space"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/state-space/cli/releases/download/v0.0.11/state-space_linux_x86_64"
        sha256 "50fc98c642ebc2cc9d5552acf29acaa8e0cd6e243ecba2ace7108a04b50aa8f3"

        def install
          bin.install "state-space_linux_x86_64" => "state-space"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/state-space/cli/releases/download/v0.0.11/state-space_linux_arm64"
        sha256 "ce65a029d2aa60890cc68368f8f71204bbedf71c4a48472e3aa069f2d0527a94"

        def install
          bin.install "state-space_linux_arm64" => "state-space"
        end
      end
    end
  end

  test do
    system "#{bin}/state-space --version"
  end
end
