# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI application to interface with State Space"
  homepage "https://state.space"
  version "0.0.13"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/state-space/cli/releases/download/v0.0.13/state-space_darwin_x86_64"
      sha256 "68ec92ca08afd76885f84e6c160b397156f5532491d5a6adca613e1ce43b9cf5"

      def install
        bin.install "state-space_darwin_x86_64" => "state-space"
      end
    end
    on_arm do
      url "https://github.com/state-space/cli/releases/download/v0.0.13/state-space_darwin_arm64"
      sha256 "94a33efa37d09f523c76e593e617be07676d9c4815e082262f55c5643c82bca0"

      def install
        bin.install "state-space_darwin_arm64" => "state-space"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/state-space/cli/releases/download/v0.0.13/state-space_linux_x86_64"
        sha256 "cd049c16b2bd4367dfc705f56c9c26d8e4a9935f2a17f427b6e566a5528d615b"

        def install
          bin.install "state-space_linux_x86_64" => "state-space"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/state-space/cli/releases/download/v0.0.13/state-space_linux_arm64"
        sha256 "05edbd6f2319790e9536dab5a4eb3f604ba10b841ce5540f186ceee852e1c231"

        def install
          bin.install "state-space_linux_arm64" => "state-space"
        end
      end
    end
  end

  test do
    system "#{bin}/state-space --version"
  end
end
